# Generated by Django 4.0.3 on 2022-04-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
