# Generated by Django 4.0.3 on 2022-04-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='passive_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_await_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateTimeField(null=True, verbose_name='Time when project/task was finished'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Name of task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Very high', 'Very important'), ('High', 'High'), ('Middle', 'Middle'), ('Low', 'Low'), ('Very low', 'Very low')], max_length=40, verbose_name='Priority of project/task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time when project/task was created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In work', 'In work'), ('Canceled', 'Canceled'), ('Finished', 'Finished'), ('Awaiting', 'Awaiting')], max_length=40, verbose_name='Status of project/task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateTimeField(null=True, verbose_name='Time when project/task was finished'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Name of task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='planned_date',
            field=models.DateTimeField(verbose_name='Planned end date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Very high', 'Very important'), ('High', 'High'), ('Middle', 'Middle'), ('Low', 'Low'), ('Very low', 'Very low')], max_length=40, verbose_name='Priority of project/task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time when project/task was created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In work', 'In work'), ('Canceled', 'Canceled'), ('Finished', 'Finished'), ('Awaiting', 'Awaiting')], max_length=40, verbose_name='Status of project/task'),
        ),
    ]
